name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout sources"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Cache Gradle"
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: "Setup Java"
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: "Build APKs"
        run: ./gradlew --no-daemon :play-services-core:assembleMapboxDefault :play-services-core:assembleMapboxHuawei

      - name: "Move APKs to Release Directory"
        run: |
          mkdir -p artifacts
          mv play-services-core/build/outputs/apk/mapboxDefault/release/*.apk artifacts/gmscore.apk
          mv play-services-core/build/outputs/apk/mapboxHuawei/release/*.apk artifacts/gmscore-huawei.apk

      - name: "Calculate SHA256 checksums for APKs"
        id: sha256_apk
        run: |
          checksums=""
          for apk in $(find ./artifacts -type f -name "*.apk"); do
            sha256=$(sha256sum "$apk" | awk '{print $1}')
            filename=$(basename "$apk")
            checksums="$checksums$filename: $sha256\n"
          done
          echo "checksums=$checksums" >> $GITHUB_ENV

      - name: "Create GitHub Release"
        id: create_release
        uses: softprops/action-gh-release@v2.0.7
        with:
          tag_name: "v${{ env.datetime }}"
          name: "Release ${{ env.datetime }}"
          body: |
            Automated release from actions.
            SHA256 checksums:
            ${{ env.checksums }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Upload APKs to release"
        uses: softprops/action-gh-release@v2.0.7
        with:
          tag_name: "v${{ env.datetime }}"
          files: ./artifacts/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
